# Generated by Django 2.2 on 2019-04-18 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190418_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='invitees_btech',
            field=models.ManyToManyField(blank=True, help_text=' (Press Ctrl to select multiple)', to='events.Btech'),
        ),
        migrations.AlterField(
            model_name='event',
            name='invitees_mtech',
            field=models.ManyToManyField(blank=True, help_text=' (Press Ctrl to select multiple)', to='events.Mtech'),
        ),
        migrations.AlterField(
            model_name='event',
            name='invitees_phd',
            field=models.ManyToManyField(blank=True, to='events.PhD'),
        ),
    ]
