# Generated by Django 2.2 on 2019-04-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20190418_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='approval',
            field=models.CharField(choices=[('Appr', 'Approved'), ('Pend', 'Pending'), ('Decl', 'Declined')], default='Pend', max_length=50),
        ),
    ]
