# Generated by Django 2.2 on 2019-04-18 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_appfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='requestor',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
