# Generated by Django 2.2 on 2019-04-18 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20190418_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='faq_a_1',
            new_name='faq_answer_1',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='faq_a_2',
            new_name='faq_answer_2',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='faq_a_3',
            new_name='faq_answer_3',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='faq_a_4',
            new_name='faq_answer_4',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='faq_a_5',
            new_name='faq_answer_5',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='faq_q_1',
            new_name='faq_question_1',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='faq_q_2',
            new_name='faq_question_2',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='faq_q_3',
            new_name='faq_question_3',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='faq_q_4',
            new_name='faq_question_4',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='faq_q_5',
            new_name='faq_question_5',
        ),
    ]
