# Generated by Django 2.2 on 2019-04-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_eventfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='curr_audience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
