# Generated by Django 2.2 on 2019-04-19 17:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_event_curr_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, help_text='Unique ID for this particular event', primary_key=True, serialize=False),
        ),
    ]
