# Generated by Django 2.2 on 2019-04-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20190419_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='faq_android',
        ),
        migrations.AddField(
            model_name='event',
            name='image_string',
            field=models.TextField(blank=True, default='None'),
        ),
    ]
