# Generated by Django 2.2 on 2019-04-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20190419_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='appfeedback',
            name='rating_1',
            field=models.FloatField(default=3.0),
        ),
        migrations.AddField(
            model_name='appfeedback',
            name='rating_2',
            field=models.FloatField(default=3.0),
        ),
        migrations.AddField(
            model_name='appfeedback',
            name='rating_3',
            field=models.FloatField(default=3.0),
        ),
        migrations.AlterField(
            model_name='appfeedback',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
