# Generated by Django 2.2 on 2019-04-19 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20190419_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appfeedback',
            old_name='rating_1',
            new_name='rating_overall',
        ),
        migrations.RenameField(
            model_name='appfeedback',
            old_name='rating_2',
            new_name='rating_ui',
        ),
        migrations.RenameField(
            model_name='appfeedback',
            old_name='rating_3',
            new_name='rating_ux',
        ),
    ]
