# Generated by Django 2.2 on 2019-04-20 05:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20190419_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='id',
        ),
        migrations.AddField(
            model_name='poll',
            name='user_id',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='poll',
            name='event_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique poll id', primary_key=True, serialize=False),
        ),
    ]
