# Generated by Django 2.2 on 2019-04-20 05:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20190420_0502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_id', models.UUIDField(default=uuid.uuid4, help_text='Unique vote id')),
                ('user_id', models.CharField(default='', max_length=300)),
                ('user_vote', models.PositiveIntegerField()),
            ],
        ),
    ]
