# Generated by Django 2.2 on 2019-04-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_remove_event_target_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.CharField(choices=[('Lecture Hall 1', 'Lecture Hall 1'), ('Lecture Hall 2', 'Lecture Hall 2'), ('Lecture Hall 3', 'Lecture Hall 3'), ('Lecture Hall 4', 'Lecture Hall 4'), ('Conference Room', 'Conference Room'), ('CSE Seminar Room', 'CSE Seminar Room'), ('Core 2 Rooms', 'Core 2 Rooms'), ('Core 5 Rooms', 'Core 5 Rooms'), ('Mini Auditorium', 'Mini Auditorium'), ('Main Auditorium', 'Main Auditorium'), ('Department Library', 'Department Library')], default='CSE Seminar Room', max_length=50),
        ),
    ]
