# Generated by Django 2.2 on 2019-04-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_auto_20190420_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='appfeedback',
            name='submitted_by',
            field=models.CharField(default='Anonymous', max_length=150),
        ),
    ]
