# Generated by Django 2.2 on 2019-04-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_appfeedback_submitted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='curr_audience',
            field=models.IntegerField(default=0),
        ),
    ]
