# Generated by Django 2.2 on 2019-04-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_auto_20190420_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.CharField(blank=True, help_text=' (Press Ctrl to select multiple)', max_length=300),
        ),
    ]
